$bibtex_use = 1.5;
$cleanup_includes_cusdep_generated = 1;
$cleanup_includes_generated = 1;
$aux_dir = "_latexmk";
$pdf_mode = 5;	# NOTE: XeLaTeX need "\usepackage{newtxtext}" to properly handle bold fonts
$silent = 1;

# SyncTeX
push(@generated_exts, ("synctex.*"));
push(@extra_xelatex_options, '-synctex=1') ;
