#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}

# ~/ Clean-up:
alias \
	monerod="monerod --data-dir ${XDG_DATA_HOME}/bitmonero" \
	yarn="yarn --use-yarnrc ${XDG_CONFIG_HOME}/yarn/config" \
	dosbox="dosbox -conf ${XDG_CONFIG_HOME}/dosbox/dosbox.conf" \
	monerod="monerod --data-dir $XDG_DATA_HOME/Monero" \
	monero-wallet-gui="monero-wallet-gui --log-file=$XDG_DATA_HOME/Monero/monero-wallet-gui.log"

# breakin the habit
alias \
	which="echo use this command instead @ type"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"
	#rsync="rsync -rtvzP"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -hAN --color=auto --group-directories-first" \
	ll="ls -hAlN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="pipe-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura" \
	za="zaread" \
	sd="setsid -f samedir" \
	pacmanfix="sudo rm -R /var/lib/pacman/sync" \
	streamit="streamlink --twitch-low-latency -p mpv -a '--cache=yes --demuxer-max-bytes=750k'" \
	download="xargs -n 1 curl -LO < ./downloadList.txt"

# function aliases
gitignore_fix() {
	git rm -r --cached .
	git add -A
	git commit -am "fixed untracked files"
}
tojpg() {
	convert "$1" "${1%.*}.jpg"
	rm "$1"
}
topdf() {
	lowwriter --headless --convert-to pdf "$1"
	rm -i "$1"
}

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
