#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv rsm pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# pass aliases to sudo
alias sudo='sudo '

# ~/ Clean-up:
[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"
[ -d "$MONERODIR" ] && alias monerod="monerod --data-dir $MONERODIR --log-file $MONERODIR/bitmonero.log" \
			monero-wallet-gui="monero-wallet-gui --log-file=$MONERODIR/monero-wallet-gui.log"

alias \
	yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config" \
	dosbox="dosbox -conf $XDG_CONFIG_HOME/dosbox/dosbox.conf" \
	svn="svn --config-dir \"$XDG_CONFIG_HOME\"/subversion" \
	mvn="mvn -gs \"$XDG_CONFIG_HOME\"/maven/settings.xml" \
	adb='HOME="$XDG_DATA_HOME"/android adb'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata --embed-chapters -i" \
	yta="yt -x -f bestaudio/best --embed-thumbnail --audio-format flac" \
	ffmpeg="ffmpeg -hide_banner" \
	rsync="rsync -vrPlu"

# Colorize commands when possible.
alias \
	ls="eza --icons --group-directories-first --color=always --time=accessed" \
	la="eza --all --icons --group-directories-first --color=always --group --time=accessed" \
	ll="eza --all --long --icons --group-directories-first --color=always --group --time=accessed" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="pipe-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura" \
	za="zaread" \
	pacmanfix="sudo rm -R /var/lib/pacman/sync" \
	download="xargs -n 1 curl -LO < ./downloadList.txt"

# function aliases
gitignore_fix() {
	git rm -r --cached .
	git add -A
	# git commit -am "fixed untracked files"
}
se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice";
}

pip() {
    if [ $1 = "search" ]; then
        pip_search "$2";
    else pip "$@";
    fi;
};

share() {
	curl -F 'sprunge=<-' http://sprunge.us ;
}

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
