#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# not set by default
export XDG_CURRENT_DESKTOP="dwm"
export XDG_SESSION_DESKTOP="dwm"
export XDG_SESSION_TYPE="x11"

# D-Bus:
export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus &

# Launching gnome-keyring-daemon outside desktop environments
dbus-update-activation-environment --all

# TODO: replace with ssh-tpm-agent
dbus-launch ssh-agent dwm
