#!/bin/bash

# Days in cache
DAYSIC=30

# Package versions
PACVERS=2

# Function to count files matching a pattern
count_files() {
    local pattern="$1"
    /usr/bin/find /var/cache/pacman/pkg/ -mindepth 1 -name "$pattern" -mtime +"$DAYSIC" | wc -l
}

# Count packages to delete older than $DAYSIC days
FILECOUNT1=$(count_files '*')

if [ "$FILECOUNT1" -gt 0 ]; then
	echo -n "Deleting $FILECOUNT1 files older than $DAYSIC days... "
fi

# Count files with more than $PACVERS versions
CANDIPAC=$(/usr/bin/paccache -d -k "$PACVERS" 2>&1)

if ! echo "$CANDIPAC" | grep -q 'no candidate packages found'; then
	FILECOUNT2=$(echo "$CANDIPAC" | grep -E 'run.*candidates' | awk '{print $1}')
	if [[ "$FILECOUNT2" =~ ^[0-9]+$ && "$FILECOUNT2" -gt 0 ]]; then
		if [ "$FILECOUNT1" -gt 0 ]; then
			echo "and $FILECOUNT2 files have more than $PACVERS versions in the cache directory."
		else
			echo "Deleting $FILECOUNT2 files with more than $PACVERS versions in the cache directory."
		fi
	fi
fi

# Delete files older than $DAYSIC days from the cache dir
/usr/bin/find /var/cache/pacman/pkg/ -mindepth 1 -name '*' -mtime +"$DAYSIC" -delete

# Delete more than $PACVERS versions of a package
/usr/bin/paccache -r -q -k "$PACVERS"

# Display disk usage after cleanup
/usr/bin/du -smh /var/cache/pacman/pkg
